name: Truffle Unittests

on:
  push:
    branches:
    - main

  pull_request:
    branches:
      - "*"
jobs:
  run_truffle_unittests:
    runs-on: ubuntu-latest
    name: Run the Truffle unit tests
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: yarn compile
    - run: yarn testrpc &
    - run: yarn test
